### ISSUE TITLE
Unexpected String?

### ISSUE THREAD

**Issue by Miirik** [mmyers/eug#36]
May 15, 2022 1:29:05 PM editor.MapPanel initialize
INFO: Reading map from image...
May 15, 2022 1:29:06 PM editor.MapPanel initialize
INFO: Done.
May 15, 2022 1:29:06 PM editor.EditorUI setDataSource
INFO: Loading saved game...
Loading C:\Users\micha\OneDrive\Documents\Paradox Interactive\Europa Universalis IV\save games\Austria1444_11_11.eu4.
C:\Users\micha\OneDrive\Documents\Paradox Interactive\Europa Universalis IV\save games\Austria1444_11_11.eu4: Warning: Unexpected string: EU4txt on line 1
C:\Users\micha\OneDrive\Documents\Paradox Interactive\Europa Universalis IV\save games\Austria1444_11_11.eu4: Warning: Unexpected string: map_area_data on line 38

Everything seems to be going fine up until this point - I can't for the life of me put my finger on the issue, though I'm by no means an expert.

**Comment by mmyers** [comment]
This happens in every save game. All saves of newer Paradox games begin with a single token identifying what game and format it is saved in, here "EU4txt". This causes the warning because it isn't a key-value pair like the entire rest of the file. E.g. the first few lines of the file might look like:

```
EU4txt
date=1748.1.1
save_game="Sweden1701_09_04_v1_30.eu4"
player="SWE"
displayed_country_name="Sweden"
```

It shouldn't keep the editor from continuing to run. Are you encountering other issues?
